<?php

declare(strict_types=1);

namespace Fundly\Integration\Ports\KeyManagement;

/**
 * Key-encryption-key operations (register I-32, FR-SEC-016). Data keys are
 * generated by the platform and only ever stored wrapped by a KEK held here:
 * local keyfile (MVP), Vault Transit or a PKCS#11 HSM later.
 */
interface KeyManagementPort
{
    public function currentKekId(): string;

    public function wrap(string $dataKey, string $context): WrappedKey;

    public function unwrap(WrappedKey $wrapped, string $context): string;

    /** Re-wrap under the current KEK (KEK rotation) without exposing the key to callers. */
    public function rewrap(WrappedKey $wrapped, string $context): WrappedKey;
}
