"""Task catalogue for 06-development-plan / progress-tracker.
Each task: (id, title, owner, size, delivers, completes, deps)
delivers  = requirement IDs whose FIRST delivery is this task (BRD ID where one exists, else LOS ID)
completes = partial requirements (phase_map.COMPLETES) whose completing increment is this task
"""
T = []
def t(id, title, owner, size, delivers="", completes="", deps=""):
    T.append(dict(id=id, title=title, owner=owner, size=size,
                  delivers=delivers.split(), completes=completes.split(), deps=deps.split()))

# ---------------- P0 Foundation ----------------
t("P0-ORC-01", "Monorepo scaffold (TRD §2.2), Pint, Larastan L8, Deptrac module rules, ESLint/tsc strict, Ruff/mypy, PR template, CODEOWNERS, traceability CI job (Pest groups → 08 matrix)", "tech-lead", "M", "LOS-CON-013")
t("P0-DEV-01", "CI pipeline stages (TRD §13): lint, static, test, contract, Semgrep, composer/npm audit, Trivy, Gitleaks, ZAP baseline; cosign-signed OCI images; CycloneDX SBOM", "devops", "M", "NFR-009 LOS-CON-010 LOS-CON-011", deps="P0-ORC-01")
t("P0-DEV-02", "Single-node compose profile (api, worker, scheduler, nginx, PG16, Redis, MinIO+Object Lock, ClamAV, Gotenberg, OTel collector); egress allow-list test proving no external SaaS on core paths", "devops", "M", "LOS-CON-012", deps="P0-ORC-01")
t("P0-OBS-01", "Correlation-ID middleware, OTel PHP SDK, Monolog JSON, RED metrics, health/readiness endpoints", "devops", "M", "NFR-011", deps="P0-DEV-02")
t("P0-ARC-01", "OpenAPI 3.1 source tree, Spectral ruleset (RFC 9457 problems, Idempotency-Key, security scheme per operation), response validator in Pest, oasdiff gate, SPA client generation", "architect", "M", "NFR-019 LOS-CON-001", deps="P0-ORC-01")
t("P0-ARC-02", "ADRs + module Contracts namespaces M01–M21, domain-event catalogue, problem-type catalogue, permission catalogue v0", "architect", "S", "", deps="P0-ORC-01")
t("P0-PLT-01", "Shared kernel: UUIDv7, Money (numeric(20,4), float ban rule), Clock, CommandBus enforcing policy→validate→mutate→audit→outbox in one transaction, event-store primitive", "be-platform", "L", "LOS-CON-004", deps="P0-ARC-02")
t("P0-DB-01", "Tenancy: tenants, legal_entities, org_units + closure table; TenantScope; FORCE RLS on every tenant table; non-owner app role; SET LOCAL app.tenant_id per transaction; cross-tenant test kit", "database", "L", "FR-TEN-001 FR-TEN-003", deps="P0-PLT-01")
t("P0-AUD-01", "Hash-chained audit_events (partitioned, per-tenant seq, advisory lock), UPDATE/DELETE/TRUNCATE trigger, INSERT/SELECT-only grants, checkpoints, audit:verify, named system identities, retention independent of operational purge", "database", "L", "FR-AUD-001 FR-AUD-002 FR-AUD-003 FR-AUD-004 FR-AUD-005 FR-AUD-012", deps="P0-DB-01 P0-PLT-01")
t("P0-PLT-02", "Configuration artefact lifecycle (draft→review→approved→active), versioning, config layer model (§17 layers 1–6)", "be-platform", "M", "FR-TEN-009 LOS-FR-284 LOS-CON-003", deps="P0-SEC-02")
t("P0-SEC-01", "Permission catalogue, roles, assignments with all scope dimensions, deny-by-default, union of assignments, field-level control, ScopeFilter for lists, policy-middleware arch test", "be-platform", "L", "FR-SEC-001 FR-SEC-002 FR-SEC-003 FR-SEC-004 FR-SEC-005 LOS-CON-007", deps="P0-DB-01")
t("P0-SEC-02", "SoD matrix (assignment-time + action-time), generic maker-checker engine (change_requests, fail-stale), time-bound assignments and elevation", "be-platform", "L", "FR-SEC-006 FR-SEC-007 FR-SEC-008", deps="P0-SEC-01 P0-AUD-01")
t("P0-SEC-03", "Local identity store (Argon2id, offline breached-password list, lockout), TOTP MFA, step-up, Sanctum SPA session (__Host- cookie, CSRF), idle/absolute timeouts, concurrent-session cap, revoke on role change", "be-platform", "L", "LOS-FR-302 FR-SEC-013 FR-SEC-015", deps="P0-SEC-01")
t("P0-SEC-04", "Standard role library (19 templates), effective-access view, service-account principals under the same policy layer", "be-platform", "M", "LOS-FR-278 FR-SEC-011 FR-SEC-014", deps="P0-SEC-02")
t("P0-SEC-05", "KeyManagementPort (local keyfile), per-tenant DEK envelope encryption, field-level encryption + blind indexes, TLS 1.3 config, masked-by-default serialisation, /pii/unmask with purpose + step-up + pii_access_log", "security-compliance", "L", "FR-SEC-016 FR-SEC-017 FR-CMP-036 LOS-CON-009", deps="P0-SEC-03 P0-AUD-01")
t("P0-SEC-06", "AppSec baseline: rate limits, FormRequest/JSON Schema validation, CSP, upload hardening policy, auth-event logging; threat model v1; ASVS 4.0.3 checklist v0", "security-compliance", "M", "FR-SEC-019 FR-AUD-007", deps="P0-SEC-03")
t("P0-INT-01", "Integration/Ports namespace, canonical CBI v1.0 contract (OpenAPI/JSON Schema), adapter registry and binding model, vendor-identifier arch test, same pattern for every port", "integration", "M", "FR-CBA-001 FR-CBA-002 FR-CBA-020 LOS-CON-002", deps="P0-ARC-02")
t("P0-INT-02", "Integration Runtime: transactional outbox + dispatcher, idempotency-key store, retry/backoff/jitter, Redis circuit breaker + alert, error taxonomy, integration_calls log (PII-masked), exception queue", "be-disbursement", "L", "FR-CBA-007 FR-CBA-008 FR-CBA-010 FR-CBA-011 FR-CBA-016 LOS-CON-005 LOS-CON-008", deps="P0-INT-01 P0-PLT-01")
t("P0-LIC-01", "LicensingPort + OfflineSignedFileLicensing (Ed25519, installation fingerprint), enforcement points, D-034 fail-safe exemptions, T-60/30/7 warnings, licence import via maker-checker", "be-platform", "M", "LOS-FR-316", deps="P0-SEC-02")
t("P0-UX-01", "Design-system port: AuditPro components → TS, Fundly v3 tokens contrast-corrected (D-027, G-46), WCAG 2.2 AA token audit, auth screen designs", "ux", "M", "", deps="P0-ORC-01")
t("P0-FE-01", "SPA shell: React 19/Vite/TS strict, generated client only, routing, TanStack Query, auth/MFA/step-up/session-expiry flows, effective-access screen, Playwright+axe scaffold", "frontend", "L", "", deps="P0-ARC-01 P0-UX-01 P0-SEC-03")
t("P0-QA-01", "Test harness: Pest + PG service container, factories, role×endpoint authorisation-matrix generator, RLS cross-tenant suite, audit-chain tamper tests, coverage gates", "qa", "M", "", deps="P0-ORC-01 P0-DB-01")
t("P0-REQ-01", "Acceptance criteria for all P0/P1 requirements; 08-traceability-matrix generator wired to phase_map.py and Pest groups", "req-analyst", "M", "", deps="P0-ORC-01")
t("P0-DOC-01", "Developer guide, ADR index, API style guide, contribution rules (D-035), runbook skeleton", "docs", "S", "", deps="P0-ARC-01")

# ---------------- P1 MVP origination ----------------
t("P1-PLT-01", "Reference data, calendars, FX rates, multi-currency, effective-dated prudential parameters (maker-checker), jurisdiction-pack resolution by legal entity, en-NG formatting", "be-platform", "M", "FR-TEN-006 FR-TEN-007 LOS-FR-307 LOS-FR-310 NFR-017", deps="P0-PLT-02")
t("P1-PLT-02", "Admin console API for layers 1–4 (products, rules, matrices, users, workflow JSON), configuration validator, live config without restart", "be-platform", "M", "FR-CFG-001 FR-CFG-002 NFR-012", deps="P0-PLT-02")
t("P1-SEC-01", "LDAP/AD bind + group mapping (DirectoryPort), Auditor role (read-only, unrestricted scope)", "be-platform", "M", "LOS-FR-305 LOS-FR-279", deps="P0-SEC-03 P0-SEC-04")
t("P1-PRD-01", "Product factory: products/versions, categories, terms/fees/interest basis, conditional checklists, bound workflow/policy/matrix, effective-dated versioning with in-flight pinning", "be-origination", "L", "FR-PRD-001 FR-PRD-002 FR-PRD-003 FR-PRD-004 FR-PRD-005 FR-PRD-006", deps="P1-PLT-02")
t("P1-PRD-02", "CBA product/GL/branch/currency/customer-type mapping per binding (maker-checker)", "integration", "M", "FR-PRD-009 FR-CBA-012", deps="P1-PRD-01 P0-INT-01")
t("P1-CHN-01", "Staff-assisted channel + API capture, channel attribution, save-and-resume with expiry, intake dedupe (blind index + trigram)", "be-origination", "M", "FR-CHN-001 FR-CHN-002 FR-CHN-003 FR-CHN-007", deps="P1-APP-01")
t("P1-CUS-01", "Party model: individual + limited company, beneficial ownership to threshold", "be-origination", "M", "FR-CUS-001 FR-CUS-006", deps="P0-SEC-05")
t("P1-CUS-02", "CBA pre-population, BVN/NIN via IdentityVerificationPort (stub), customer 360 via simulator, new-to-bank creation step", "be-origination", "M", "FR-CUS-002 FR-CUS-003 FR-CUS-009 FR-CUS-011", deps="P1-CUS-01 P1-INT-02")
t("P1-CUS-03", "Risk-based CDD rule table + progression gate, granular consent with withdrawal and history, bureau-consent precondition", "be-origination", "M", "FR-CUS-007 FR-CUS-008 FR-CMP-010 FR-CMP-021 FR-CMP-032", deps="P1-CUS-01 P1-CRD-01")
t("P1-CMP-01", "ScreeningPort (stub): intake/approval/pre-disbursement screening of all parties, evidence retention, alert workspace with four-eyes, originator-cannot-clear", "be-decisioning", "L", "FR-CUS-005 FR-CMP-011 FR-CMP-013 FR-CMP-014 FR-CMP-017", deps="P1-CUS-01 P0-SEC-02")
t("P1-APP-01", "Event-sourced application aggregate, human reference, canonical state machine + cross-cutting states, terminal states with mandatory reasons, ETag/If-Match", "be-origination", "L", "FR-APP-001 FR-APP-006 LOS-FR-282 LOS-FR-283", deps="P0-PLT-01 P0-AUD-01")
t("P1-APP-02", "Schema-driven dynamic forms, multiple applicants/guarantors, pre-approval amendment with field history, completeness indicator, field provenance", "be-origination", "L", "FR-APP-002 FR-APP-004 FR-APP-005 FR-APP-008 LOS-FR-301 NFR-013", deps="P1-APP-01 P1-PRD-01")
t("P1-APP-03", "Application- and stage-level SLA clocks over the tenant calendar with pause/resume", "be-origination", "M", "FR-APP-009", deps="P1-APP-01 P1-PLT-01")
t("P1-DOC-01", "Upload API (web + API, tus resumable), format/size policy, ClamAV gate, SHA-256 before store, Object-Lock immutable versions, hash/similarity duplicate detection", "be-origination", "L", "FR-DOC-001 FR-DOC-002 FR-DOC-004 FR-DOC-005 FR-DOC-006", deps="P1-APP-01 P0-SEC-05")
t("P1-DOC-02", "Per-application checklist with statuses, waivers via authority, expiry tracking, manual-verification IDP adapter", "be-origination", "M", "FR-DOC-007 FR-DOC-008 FR-DOC-009", deps="P1-DOC-01 P1-PRD-01")
t("P1-CRD-01", "Rules engine: sandboxed evaluator (decimal), fact schema, decision tables/trees/expressions, versioned rule sets, EVALUATOR_VERSION", "be-decisioning", "L", "FR-CRD-001 FR-CRD-002", deps="P0-PLT-02")
t("P1-CRD-02", "CreditBureauPort (one bureau stub), canonical credit profile parser, bureau-before-approval gate with pack validity window", "be-decisioning", "M", "FR-CRD-003 FR-CRD-004 FR-CMP-020", deps="P1-CRD-01 P1-CUS-03")
t("P1-CRD-03", "Decision flow: affordability formulas, structured outcome, counter-offer, immutable snapshot + replay, reason codes, exceptions/overrides escalating authority", "be-decisioning", "L", "FR-CRD-008 FR-CRD-010 FR-CRD-011 FR-CRD-014 FR-CRD-015 FR-CMP-027 FR-CMP-043 LOS-CON-006", deps="P1-CRD-01 P1-CRD-02")
t("P1-CRD-04", "Credit memo: templated sections auto-populated + analyst narrative, versioned", "be-decisioning", "M", "FR-CRD-013", deps="P1-CRD-03")
t("P1-CMP-02", "Single-obligor limit check against prudential parameters and CBA exposure", "be-decisioning", "M", "FR-CMP-023", deps="P1-PLT-01 P1-CRD-03")
t("P1-CMP-03", "Jurisdiction-pack framework: signed versioned bundle, effective-dated rule register with citations, verification_status activation gate; Nigeria × commercial bank v0", "be-decisioning", "L", "FR-CMP-001 FR-CMP-003", deps="P1-PLT-01")
t("P1-CMP-04", "Verify every Nigeria pack v0 rule against primary source (TRD §9.4); record citation, URL, retrieval and effective date; PO sign-off", "security-compliance", "M", "", deps="P1-CMP-03")
t("P1-COL-01", "Collateral: configurable types, haircuts/FSV/LTV/cover, valuations, perfection lifecycle, multi-facility allocation, insurance, disbursement block", "be-decisioning", "L", "FR-COL-001 FR-COL-002 FR-COL-003 FR-COL-004 FR-COL-005 FR-COL-006 FR-COL-008", deps="P1-APP-01 P1-CRD-01")
t("P1-WFL-01", "Workflow engine: definitions/versions, stage→canonical mapping, guards, validator, in-flight version pinning", "be-origination", "L", "FR-WFL-001 FR-WFL-012", deps="P1-APP-01 P1-CRD-01")
t("P1-WFL-02", "Routing (role/skill/branch/product/band/load), pull + push queues, reassignment and delegation with attribution, task inbox with bulk actions, case notes", "be-origination", "L", "FR-WFL-003 FR-WFL-004 FR-WFL-005 FR-WFL-009 FR-WFL-010", deps="P1-WFL-01")
t("P1-WFL-03", "Stage SLA enforcement + escalation, send-back with targeted rework, hold with SLA pause and auto-expiry, configured auto-decisions", "be-origination", "M", "FR-WFL-006 FR-WFL-007 FR-WFL-008 FR-WFL-011", deps="P1-WFL-02 P1-APP-03")
t("P1-APV-01", "Approval matrix as decision table, effective limits (min user/role/org), sequential chains, approver SoD, delegation of authority, auto-escalation", "be-decisioning", "L", "FR-APV-001 FR-APV-002 FR-APV-003 FR-APV-005 FR-APV-006 FR-APV-007", deps="P1-CRD-03 P0-SEC-02")
t("P1-APV-02", "Votes with rationale/reason codes/authority basis/step-up ref, conditional approval → CPs, decision packet, approval validity expiry", "be-decisioning", "M", "FR-APV-008 FR-APV-009 FR-APV-010 FR-APV-012", deps="P1-APV-01")
t("P1-OFR-01", "Offer templates (versioned), key-facts/cost-of-credit per pack method, schedule from CBA/LOS, Gotenberg PDF", "be-disbursement", "L", "FR-OFR-001 FR-OFR-002 FR-OFR-003 FR-CMP-025", deps="P1-APV-02 P1-CMP-03")
t("P1-OFR-02", "Offer delivery (email + printable), acceptance (wet-sign + e-sign stub), validity/reminders/re-issue, reject/negotiate loop, ordered multi-party signing, immutable executed agreement, execution method per template", "be-disbursement", "L", "FR-OFR-004 FR-OFR-005 FR-OFR-006 FR-OFR-007 FR-OFR-008 FR-OFR-009 FR-OFR-010 LOS-FR-314", deps="P1-OFR-01 P1-NTF-01")
t("P1-CPR-01", "CP/CS items, mandatory-CP hard block, pre-disbursement checklist, pre-disbursement re-screen (stub), destination name enquiry (simulator)", "be-disbursement", "M", "FR-CPR-001 FR-CPR-002 FR-CPR-003 FR-CPR-004 FR-CPR-005", deps="P1-OFR-02 P1-CMP-01")
t("P1-DSB-01", "Booking saga: ensure customer → create loan account → single disbursement → fees → schedule variance check; exactly-once keys, pending/failed sub-states, lookup-before-retry, compensation", "be-disbursement", "L", "FR-DSB-001 FR-DSB-002 FR-DSB-004 FR-DSB-005 FR-DSB-006 FR-DSB-007 FR-CBA-009 LOS-FR-313", deps="P1-CPR-01 P0-INT-02 P1-INT-02")
t("P1-DSB-02", "Disbursement maker-checker (checker ≠ maker ≠ approver, step-up), advice + final schedule, daily reconciliation runs and break queue", "be-disbursement", "M", "FR-DSB-008 FR-DSB-009 FR-DSB-011 FR-CBA-017", deps="P1-DSB-01")
t("P1-HND-01", "Booked transition, facility.created event + signed webhook, CS/collateral/insurance handover package, origination-record retention", "be-disbursement", "M", "FR-HND-001 FR-HND-003 FR-HND-004", deps="P1-DSB-01")
t("P1-NTF-01", "Notification module: email (SMTP) + in-app + webhook, templates per event/channel with maker-checker, communication log", "be-disbursement", "M", "FR-NTF-001 FR-NTF-002 FR-NTF-005", deps="P0-SEC-02 P0-INT-02")
t("P1-INT-01", "Capability manifests, unsupported-operation substitution (manual task / batch / LOS compute), sync/async/batch/MQ styles, reference-data cache (no balance caching)", "integration", "L", "FR-CBA-003 FR-CBA-004 FR-CBA-005 FR-CBA-019", deps="P0-INT-02")
t("P1-INT-02", "CBA simulator + mock providers for every MVP port with fault scripts; production-bind refusal; certification kit v1 run against simulator", "integration", "L", "FR-CBA-015 FR-CBA-013 NFR-006 NFR-018", deps="P0-INT-02")
t("P1-AUD-01", "PII/application read-access log, integration-call audit, audit explorer API, as-at temporal query, evidence pack v1, overrides/waivers report", "be-platform", "L", "FR-AUD-006 FR-AUD-008 FR-AUD-009 FR-AUD-010 FR-AUD-011 FR-AUD-016", deps="P1-APP-01 P0-INT-02")
t("P1-RPT-01", "Operational dashboard (pipeline, TAT, SLA breaches, queues) with ScopeFilter enforcement on every report", "be-platform", "M", "FR-RPT-001 FR-RPT-010", deps="P1-WFL-03")
t("P1-UX-01", "MVP screen designs per role journey (capture → booked, auditor), states, empty/error states, responsive 768 px", "ux", "L", "", deps="P0-UX-01")
t("P1-FE-01", "Admin console UI: products, rule tables, matrices, users/roles/SoD, workflow, change-request inbox", "frontend", "L", "", deps="P1-UX-01 P1-PLT-02")
t("P1-FE-02", "Origination UI: application capture, parties, consents, KYC/screening, documents and checklist", "frontend", "L", "", deps="P1-UX-01 P1-APP-02 P1-DOC-02")
t("P1-FE-03", "Assessment UI: bureau, decision result + reason codes, memo, collateral, approval packet and voting with step-up", "frontend", "L", "", deps="P1-UX-01 P1-APV-02")
t("P1-FE-04", "Execution UI: offer, CPs, disbursement maker/checker, exception and recon queues, audit explorer, evidence pack, dashboard", "frontend", "L", "", deps="P1-UX-01 P1-DSB-02 P1-AUD-01")
t("P1-FE-05", "Accessibility and browser matrix certification of MVP screens (axe on every screen, manual SR audit, Chrome/Edge/Safari/Firefox current+previous)", "frontend", "M", "NFR-014 NFR-015", deps="P1-FE-04")
t("P1-QA-01", "MVP E2E suite (demo script §2.3) in Playwright, resilience tests with fault injection, replay test against frozen snapshots", "qa", "L", "", deps="P1-FE-04")
t("P1-QA-02", "Authorisation-matrix, out-of-scope and RLS tests for every P1 endpoint; OpenAPI conformance report", "qa", "M", "", deps="P1-DSB-02")
t("P1-SEC-02", "MVP security assurance: threat-model update, ASVS L2 (L3 for V2/V3/V6/V8) checklist evidence, authenticated ZAP, SoD conflict report review", "security-compliance", "M", "", deps="P1-DSB-02")
t("P1-DEV-01", "MVP install bundle (single-node), installation-qualification checklist, nightly restore test, demo/UAT environment with simulators and synthetic data", "devops", "M", "", deps="P0-DEV-02")
t("P1-REQ-01", "UAT scripts per requirement from the matrix; P1 traceability report", "req-analyst", "M", "", deps="P0-REQ-01")
t("P1-DOC-03", "MVP user guides per role, admin guide, API guide v1, release notes v0.1", "docs", "M", "", deps="P1-FE-04")

# ---------------- P2 Documents & IDP ----------------
t("P2-IDP-01", "IDP service scaffold (Python 3.12/FastAPI, own `idp` schema, OTel, signed image) + DocumentIntelligencePort live adapter; engine replaceable per tenant", "idp", "M", "FR-DOC-054", deps="P0-INT-01")
t("P2-IDP-02", "Image pre-processing: de-skew, de-noise, crop, rotation, contrast, multi-page handling", "idp", "M", "FR-DOC-003", deps="P2-IDP-01")
t("P2-IDP-03", "Classification and bundled-PDF page splitting with routing to checklist", "idp", "L", "FR-DOC-020 FR-DOC-021", deps="P2-IDP-02")
t("P2-IDP-04", "Field and table extraction for the BRD document set, handwriting (mandatory review), tenant templates, canonical schemas", "idp", "L", "FR-DOC-022 FR-DOC-023 FR-DOC-027 FR-DOC-028 FR-DOC-029", deps="P2-IDP-03")
t("P2-IDP-05", "Per-field confidence with per-field/doc-type/tenant thresholds", "idp", "M", "FR-DOC-024", deps="P2-IDP-04")
t("P2-IDP-06", "Statement parsing (PDF/CSV/scanned/API) and transaction categorisation", "idp", "L", "FR-DOC-040 FR-DOC-041", deps="P2-IDP-04")
t("P2-IDP-07", "Income regularity, debt-service detection, affordability metrics from statements", "idp", "L", "FR-DOC-042 FR-DOC-043 FR-DOC-044", deps="P2-IDP-06")
t("P2-IDP-08", "Statement tampering, forgery indicators, cross-validation against application and other documents", "idp", "L", "FR-DOC-045 FR-DOC-050 FR-DOC-052", deps="P2-IDP-06")
t("P2-DOC-01", "HITL verification queue in LOS, correction capture as training feedback, document lineage", "be-origination", "L", "FR-DOC-025 FR-DOC-026 FR-DOC-053", deps="P2-IDP-05")
t("P2-DOC-02", "Statement-analysis drill-through API (metric → transactions)", "be-origination", "M", "FR-DOC-046", deps="P2-IDP-07")
t("P2-FE-01", "Document viewer (annotation, redaction, side-by-side, page accept/reject), HITL screen, statement analytics drill-through", "frontend", "L", "FR-DOC-010", deps="P2-DOC-01 P2-DOC-02")
t("P2-QA-01", "Nigerian document benchmark corpus (anonymised), accuracy and p95 latency harness on certified IDP node spec", "qa", "M", "NFR-003", deps="P2-IDP-04")
t("P2-SEC-01", "IDP service security review: pip audit, container scan, no-egress verification, PII handling in `idp` schema", "security-compliance", "S", "", deps="P2-IDP-01")

# ---------------- P3 Decisioning & workflow depth ----------------
t("P3-PRD-01", "Product availability rules (channel/branch/segment/date) and product simulation sandbox", "be-origination", "M", "FR-PRD-007 FR-PRD-008", deps="P1-PRD-01")
t("P3-TEN-01", "Tenant terminology overrides across UI, documents and notifications", "be-platform", "S", "FR-TEN-005", deps="P1-PLT-02")
t("P3-APP-01", "Extension attributes (JSON Schema, GIN) usable in rules/templates/reports; application cloning", "be-origination", "M", "FR-APP-003 FR-APP-007", deps="P1-APP-02")
t("P3-CUS-01", "Remaining applicant types (sole proprietor, partnership, group/cooperative)", "be-origination", "M", "", completes="FR-CUS-001", deps="P1-CUS-01")
t("P3-CUS-02", "Related-party/connected-exposure linkage and aggregated exposure (CBA + in-flight)", "be-decisioning", "L", "FR-CUS-010 FR-CRD-007", deps="P1-CUS-02")
t("P3-CRD-01", "Application and behavioural scorecards (versioned) + common scoring interface for external/local models", "be-decisioning", "L", "FR-CRD-005 FR-CRD-006", deps="P1-CRD-03")
t("P3-CRD-02", "Risk-based pricing matrices", "be-decisioning", "M", "FR-CRD-009", deps="P3-CRD-01")
t("P3-CRD-03", "Financial spreading for SME/corporate (manual + extracted), ratios, projections", "be-decisioning", "L", "FR-CRD-012", deps="P1-CRD-03")
t("P3-CRD-04", "Decision-time fraud checks: velocity, device/IP, internal blacklist", "be-decisioning", "M", "FR-CRD-017", deps="P1-CRD-03")
t("P3-CRD-05", "Historical application import and simulation against stored snapshots with outcome diff", "be-decisioning", "M", "LOS-FR-308", completes="FR-CRD-002", deps="P1-CRD-03")
t("P3-WFL-01", "Parallel branches with join conditions; out-of-office cover", "be-origination", "L", "FR-WFL-002", completes="FR-WFL-005", deps="P1-WFL-03")
t("P3-APV-01", "Parallel and quorum approval; committee workflow (agenda, packet, e-voting, minutes); mobile approval with step-up", "be-decisioning", "L", "FR-APV-004 FR-APV-011", completes="FR-APV-003", deps="P1-APV-02")
t("P3-CMP-01", "Insider/related-party register, automatic insider flag + elevated path, sector/insider limits", "be-decisioning", "M", "LOS-FR-306 FR-CMP-024", completes="FR-CMP-023", deps="P3-CUS-02")
t("P3-CMP-02", "Model inventory, validation record + maker-checker before activation, drift monitoring", "be-decisioning", "M", "FR-CMP-040 FR-CMP-041 FR-CMP-042", deps="P3-CRD-01")
t("P3-CPR-01", "Post-disbursement conditions subsequent tracking, servicing handover, breach escalation", "be-disbursement", "M", "FR-CPR-006", deps="P1-HND-01")
t("P3-DSB-01", "Tranched/milestone, revolving activation, third-party payout modes; tranche conditions/approval/release", "be-disbursement", "L", "FR-DSB-003", completes="FR-DSB-002", deps="P1-DSB-02")
t("P3-DSB-02", "Disbursement cancellation/reversal within window with compensating CBA instructions", "be-disbursement", "M", "FR-DSB-012", deps="P1-DSB-02")
t("P3-HND-01", "Post-booking audited amendment process", "be-disbursement", "M", "FR-HND-005", deps="P1-HND-01")
t("P3-UX-01", "Designs: committee, spreading, scorecard/simulation diff, parallel tasks, mobile approval", "ux", "M", "", deps="P1-UX-01")
t("P3-FE-01", "UI for P3 capabilities incl. mobile-responsive approval", "frontend", "L", "", deps="P3-UX-01 P3-APV-01 P3-CRD-03")
t("P3-QA-01", "Replay and simulation regression, committee E2E, tranche saga fault tests", "qa", "M", "", deps="P3-DSB-01 P3-APV-01")

# ---------------- P4 Live integrations & channels ----------------
t("P4-INT-01", "Finacle live adapter: mappings, error map, manifest, certification kit against Finacle sandbox", "integration", "L", "", completes="FR-CUS-009", deps="P1-INT-02")
t("P4-INT-02", "Generic file + manual-queue fallback CBA adapter", "integration", "M", "FR-CBA-006", deps="P1-INT-01")
t("P4-INT-03", "NIBSS BVN / NIMC NIN live, liveness/selfie match, issuing-authority verification (CAC, FIRS)", "integration", "L", "FR-CUS-004 FR-DOC-051", completes="FR-CUS-003", deps="P1-CUS-02")
t("P4-INT-04", "Live bureaus (CRC, FirstCentral, CreditRegistry) with selection and fallback order", "integration", "L", "", completes="FR-CRD-003", deps="P1-CRD-02")
t("P4-INT-05", "Screening provider live, offline list snapshots, watchlist-update batch re-screen", "integration", "L", "FR-CMP-012", completes="FR-CUS-005 FR-CPR-004 FR-CMP-013", deps="P1-CMP-01")
t("P4-INT-06", "Payments (NIP name enquiry/transfer), e-mandate/standing instruction, Remita/payroll verification, GSI consent", "integration", "L", "FR-DSB-010 LOS-FR-287 LOS-FR-315 LOS-FR-311", completes="FR-CPR-005", deps="P1-DSB-01")
t("P4-INT-07", "E-signature provider live (in-country/on-prem processing)", "integration", "M", "", completes="FR-OFR-006", deps="P1-OFR-02")
t("P4-INT-08", "Valuation, insurance and collateral-registry adapters", "integration", "L", "LOS-FR-285 LOS-FR-286 FR-COL-007", deps="P1-COL-01")
t("P4-INT-09", "Records/DMS handover (CMIS / file drop)", "integration", "M", "FR-HND-002", deps="P1-HND-01")
t("P4-INT-11", "AtherisLicensingServer adapter behind LicensingPort (online check-in, activation, revocation). Blocked until the G-48 contract is received; pull forward as soon as it arrives", "be-platform", "M", "", deps="P0-LIC-01")
t("P4-INT-10", "Processing-location declaration in manifests; activation refused on residency breach", "be-disbursement", "S", "LOS-FR-309", deps="P1-INT-01")
t("P4-NTF-01", "SMS, WhatsApp, Web Push channels; communication preferences/opt-out; duplicate suppression, rate limits, quiet hours", "be-disbursement", "M", "LOS-FR-304 FR-NTF-003 FR-NTF-006", completes="FR-NTF-001 FR-OFR-004", deps="P1-NTF-01")
t("P4-SEC-01", "SAML 2.0/OIDC SSO + SCIM 2.0, WebAuthn, IP allow-list and device binding", "be-platform", "L", "FR-SEC-012 FR-SEC-020", deps="P1-SEC-01")
t("P4-CHN-01", "Applicant portal API (/portal/v1) with OTP auth, status tracking and outstanding-item prompts", "be-origination", "L", "LOS-FR-303 FR-NTF-004", deps="P1-APP-02")
t("P4-CHN-02", "Leads (capture/assign/convert/loss reason) and indicative pre-qualification", "be-origination", "M", "FR-CHN-005 FR-CHN-006", deps="P1-CHN-01")
t("P4-CHN-03", "Partner API (/partner/v1), partner-scoped credentials and rate limits, Partner/DSA own-submissions role", "be-origination", "L", "FR-CHN-008 LOS-FR-281", deps="P4-SEC-01")
t("P4-CHN-04", "Canonical bulk-upload template with row-level validation report", "be-origination", "M", "LOS-FR-312", deps="P1-APP-02")
t("P4-FE-01", "Applicant/agent PWA: apply, upload (camera, resumable), track, accept offer; offline capture with conflict-safe sync; low-bandwidth budget", "frontend", "L", "FR-CHN-004 NFR-016", completes="FR-CHN-001 FR-DOC-001", deps="P4-CHN-01")
t("P4-UX-01", "Portal/agent PWA designs and low-bandwidth patterns", "ux", "M", "", deps="P1-UX-01")
t("P4-SEC-02", "External-facing surface assurance: portal/partner threat model, ZAP authenticated + targeted pen test of /portal and /partner", "security-compliance", "M", "", deps="P4-CHN-03 P4-FE-01")
t("P4-QA-01", "Certification-kit runs per live adapter; contract tests; portal E2E on throttled network", "qa", "M", "", deps="P4-INT-01 P4-FE-01")

# ---------------- P5 Compliance, reporting & data ----------------
t("P5-TEN-01", "Tenant branding (letterhead, templates, domains) and multi-language UI/documents", "be-platform", "M", "FR-TEN-004 FR-TEN-008", deps="P1-PLT-02")
t("P5-CFG-01", "Config export/import between environments, diff and rollback, onboarding accelerator templates", "be-platform", "L", "FR-TEN-010 FR-TEN-011 FR-CFG-003", completes="FR-CFG-001", deps="P1-PLT-02")
t("P5-CMP-01", "Source of funds/wealth capture at EDD; goAML-shaped STR extracts [verify schema]", "be-decisioning", "M", "FR-CMP-015 FR-CMP-016", deps="P1-CUS-03")
t("P5-CMP-02", "CRMS origination obligations and regulatory report generation with submission log", "be-decisioning", "L", "FR-CMP-022 FR-RPT-006", deps="P1-CMP-03")
t("P5-CMP-03", "Adverse action notices, human review of automated decisions, fair-lending distributions (DPIA flag)", "be-decisioning", "M", "FR-CMP-026 FR-CMP-044 FR-CMP-045", deps="P1-CRD-03")
t("P5-CMP-04", "NDPA/GAID: data inventory from annotations, DSR workflow, retention + purge/anonymise + legal hold, residency, processor register", "be-decisioning", "L", "FR-CMP-030 FR-CMP-031 FR-CMP-033 FR-CMP-034 FR-CMP-035 FR-CMP-037", deps="P1-AUD-01")
t("P5-CMP-05", "Nigeria commercial-bank pack v1: complete rule set, all rules verified (TRD §9.3 items), pack signing and activation", "security-compliance", "M", "", completes="FR-CMP-001", deps="P5-CMP-02 P5-CMP-04")
t("P5-AUD-01", "SIEM streaming (CEF/JSON syslog-TLS), suspicious-pattern alerts; evidence pack with Ed25519-signed manifest", "be-platform", "M", "FR-AUD-014 FR-AUD-015", completes="FR-AUD-010", deps="P1-AUD-01")
t("P5-SEC-01", "Break-glass, access recertification campaigns, deterministic anonymiser + refresh guard, Regulator/Examiner time-bound role", "be-platform", "L", "FR-SEC-009 FR-SEC-010 FR-SEC-018 LOS-FR-280", deps="P0-SEC-04")
t("P5-RPT-01", "Management, risk, productivity and funnel reporting", "be-platform", "L", "FR-RPT-002 FR-RPT-003 FR-RPT-004 FR-RPT-005", completes="FR-RPT-001", deps="P1-RPT-01")
t("P5-RPT-02", "Governed semantic layer for user-defined reports, scheduled delivery (CSV/XLSX/PDF) with export log, DWH extract/CDC feed", "be-platform", "L", "FR-RPT-007 FR-RPT-008 FR-RPT-009", deps="P5-RPT-01")
t("P5-LIC-01", "Licence and support console: tenant lifecycle, adapter registry/version pinning, cross-installation health (no business data), time-bound operator access grants", "be-platform", "L", "LOS-FR-274 LOS-FR-275 LOS-FR-276 LOS-FR-277", deps="P0-LIC-01")
t("P5-DAT-01", "Full tenant data export in open formats (JSONL + CSV + originals + manifest)", "be-platform", "M", "NFR-020", deps="P5-CMP-04")
t("P5-FE-01", "UI for compliance workspaces, DSR, reports, console", "frontend", "L", "", deps="P5-RPT-02 P5-CMP-04")
t("P5-QA-01", "Report scope tests, DSR/retention tests (incl. legal hold), regulatory extract format tests", "qa", "M", "", deps="P5-CMP-04 P5-RPT-02")

# ---------------- P6 Hardening & certification ----------------
t("P6-TEN-01", "Dedicated isolation option (schema/database per tenant via connection resolver)", "database", "M", "FR-TEN-002", deps="P0-DB-01")
t("P6-AUD-01", "WORM certification for audit and document stores (Object Lock compliance mode, detached read-only partitions)", "database", "M", "FR-AUD-013", deps="P5-AUD-01")
t("P6-INT-01", "Adapter SDK + docs, out-of-process adapters over mTLS, hot-swap with version pinning; certification kit final", "integration", "L", "FR-CBA-014 FR-CBA-018", completes="FR-CBA-013", deps="P4-INT-01")
t("P6-CFG-01", "Upgrade-safe configuration and obsolete-config detection", "be-platform", "M", "FR-CFG-004", deps="P5-CFG-01")
t("P6-SEC-01", "Vault Transit + PKCS#11 KEK, customer-managed keys, key rotation; external pen test; ASVS evidence; CBN cybersecurity framework mapping", "security-compliance", "L", "", completes="FR-SEC-016", deps="P5-SEC-01")
t("P6-DEV-01", "HA reference profile, Helm chart, Ansible roles, signed air-gap bundle; zero-downtime upgrade N-1→N under load", "devops", "L", "NFR-010", deps="P1-DEV-01")
t("P6-DEV-02", "Synchronous standby failover, pgBackRest PITR, DR runbook and exercise", "devops", "L", "NFR-008 NFR-007", deps="P6-DEV-01")
t("P6-DEV-03", "Availability SLOs and alert pack (outbox lag, breaker, audit verify, recon, licence, replication)", "devops", "M", "NFR-005", deps="P6-DEV-01")
t("P6-QA-01", "k6 performance and scale certification at reference profile (300 staff, 2,000 apps/day), decision timing, 2→4 node scale test", "qa", "L", "NFR-001 NFR-002 NFR-004", deps="P6-DEV-01")
t("P6-DOC-01", "Installation qualification, operations runbooks, security evidence pack for bank InfoSec, v1.0 release notes", "docs", "M", "", deps="P6-SEC-01 P6-DEV-02")

V2 = "FR-PRD-010 FR-DOC-030 FR-CRD-016 FR-CMP-002".split()

# NFRs and constraints NOT phased by phase_map.py: phase proposed here, flagged for PO confirmation
PROPOSED = {
 "NFR-001": "P6", "NFR-002": "P6", "NFR-003": "P2", "NFR-004": "P6", "NFR-005": "P6", "NFR-007": "P6",
 "NFR-015": "P1", "NFR-016": "P4", "NFR-020": "P5",
}
PROPOSED.update({f"LOS-CON-{i:03d}": "P0" for i in range(1, 14)})
PROPOSED["LOS-CON-006"] = "P1"

SIZE_DAYS = {"S": 2, "M": 5, "L": 10}
